# Generated by Django 2.2 on 2020-06-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecount',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
