# Generated by Django 2.2 on 2020-06-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200619_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
